version: '3.3'

services:
  nlp:
    image: ghcr.io/aparinov/2023_iasng:dev
    container_name: nlp
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - 8004:8000
    environment:
      - CUDA_VISIBLE_DEVICES=0
volumes:
  nlp:
